### ISSUE TITLE
Custom Modpack (Error in Bloodmagic/Sanguimancy)

### ISSUE THREAD

**Issue by LocatedEagle232** [Tombenpotter/Sanguimancy#118]
The pack worked alright and then I added Sanguimancy and it crashed. Then I facepalmed and added Guide API, it crashed again. Then I fixed the Guide API version, then it loaded 6/7 in Forge, and then crashed. It says in the report, but I am running windows 10, with 1.7.10 forge and what I think is updated java. I haven't seen any similar errors so I assume either I am being extremely stupid and it is obvious or something isn't compatible. 

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/25/16 7:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: amerifrance.guideapi.pages.PageIRecipe.<init>(Lnet/minecraft/item/crafting/IRecipe;Lamerifrance/guideapi/api/abstraction/IRecipeRenderer;)V
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: amerifrance.guideapi.pages.PageIRecipe.<init>(Lnet/minecraft/item/crafting/IRecipe;Lamerifrance/guideapi/api/abstraction/IRecipeRenderer;)V
    at WayofTime.alchemicalWizardry.common.book.BloodMagicGuide.getOrbPageForRecipe(BloodMagicGuide.java:52)
    at WayofTime.alchemicalWizardry.common.book.BloodMagicGuide.registerArchitectBook(BloodMagicGuide.java:81)
    at WayofTime.alchemicalWizardry.common.book.BloodMagicGuide.registerGuide(BloodMagicGuide.java:36)
    at WayofTime.alchemicalWizardry.AlchemicalWizardry.registerBMBook(AlchemicalWizardry.java:1342)
    at WayofTime.alchemicalWizardry.AlchemicalWizardry.postInit(AlchemicalWizardry.java:1282)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 190506128 bytes (181 MB) / 403697664 bytes (384 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 30 mods loaded, 30 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJ   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJ   WitchingGadgetsCore{1.1.10} [Witching Gadgets Core](minecraft.jar) 
    UCHIJ   OpenModsCore{0.9} [OpenModsCore](minecraft.jar) 
    UCHIE   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJ   ForbiddenMagic{1.7.10-0.575} [Forbidden Magic](Forbidden Magic-1.7.10-0.575.jar) 
    UCHIJ   Automagy{0.8} [Automagy](Automagy-1.7.10-0.8.jar) 
    UCHIJ   cannibalism{1.0.1} [Cannibalism](Cannibalism-1.0.1-1.7.10.jar) 
    UCHIJ   DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
    UCHIJ   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJ   evilcraft{0.4.2b} [EvilCraft](EvilCraft-1.7.10-0.4.2b-11.jar) 
    UCHIJ   gadomancy{1.0.7.2} [Gadomancy](gadomancy-1.7.10-1.0.7.2.jar) 
    UCHIJ   guideapi{1.7.10-1.0-8} [Guide-API](Guide-API-1.7.10-1.0-8.jar) 
    UCHIJ   iChunUtil{4.1.3} [iChunUtil](iChun-Util-Mod-1.7.10.jar) 
    UCHIJ   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHIJ   necromancy{1.7.1} [Necromancy](Necromancy-1.7.10.jar) 
    UCHIJ   OpenMods{0.9} [OpenMods](OpenModsLib-1.7.10-0.9.jar) 
    UCHIJ   OpenBlocks{1.5} [OpenBlocks](OpenBlocks-1.7.10-1.5.jar) 
    UCHIE   Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy](Sanguimancy-1.7.10-1.1.9-35.jar) 
    UCHIJ   SSTOW{1.7.10-0.1-RC8-4} [Soul Shards: The Old Ways](SoulShards-TOW-1.7.10-0.1-RC8-4.jar) 
    UCHIJ   TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4 %281%29.jar) 
    UCHIJ   TravellersGear{1.16.6} [Traveller's Gear](TravellersGear-1.7.10-1.16.6.jar) 
    UCHIJ   WitchingGadgets{1.1.10} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.10.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3345' Renderer: 'Intel(R) HD Graphics 4600'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8

**Comment by TehNut** [comment]
You are using an insanely outdated version of GuideAPI on an insanely outdated version of Minecraft. Update.

**Comment by LocatedEagle232** [comment]
Thank you! It is amazing to see you comment on this because I have written your name down like 40 times on documents giving credit to mods you helped make/made :D

**Comment by Tombenpotter** [comment]
Hey @TehNut, look, you've got a fan!
