### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by OldOpa** [Tombenpotter/Sanguimancy#47]
I'm new to your mod and I did not find a way to get soul corruption in SP (how to kill a other player in SP?). When I killed a mob with no soul corruption I get this error:

Description: Ticking memory connection

java.lang.ArithmeticException: / by zero
	at tombenpotter.sanguimancy.items.corrupted.ItemCorruptedAxe.onEntityDrop(ItemCorruptedAxe.java:235)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_198_ItemCorruptedAxe_onEntityDrop_LivingDropsEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:308)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:939)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54)
	at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:222)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tombenpotter.sanguimancy.items.corrupted.ItemCorruptedAxe.onEntityDrop(ItemCorruptedAxe.java:235)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_198_ItemCorruptedAxe_onEntityDrop_LivingDropsEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:308)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:939)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54)
	at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:222)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@197f2f12
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Tombenpotter** [comment]
To get your first corruption in SSP, you have to activate the Drill of the Dead. Then you can use your corrupted tools to make it go up.
