### ISSUE TITLE
[player] seems to have misplaced a couple of hearts.

### ISSUE THREAD

**Issue by Goju-Sulfam** [Tombenpotter/Sanguimancy#51]
(sorry if this post is not grammatically perfect, English is not my native language)

I am not familiar with Blood Magic/Sanguimancie's mechanics, so it's possible i have doing a stupid thing. I have found this bug when I try to go to the Souls Network dimention to verify if Tinker Construct spawn his slime floating island in it. In 1.1.9-26 (proposed by Curse) the "Soul Transposer" is broken but at this moment i don't know this and i have tried some things. I have reproduced the crash in the last jerkin version (1.1.9-29)

crash step :

-Create a new world in survival, with cheat ON

-Give you an orb (tested with a Master Blood Orb)

-Bound it to you by using it

-Fill your network with /soulnetwork [player] fill

-Give you the "Add Soul Corruption" item

-Use it to set your corruption level at some thing hight (tested at 400)

-Get the "remove heart IV" debuff

The game crash when it try to apply the debuff with this message : 

Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.world.World.func_72939_s(World.java:1902) ~[ahb.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -105
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524) ~[sv.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293) ~[sv.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318) ~[sa.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63) ~[bjk.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
	... 10 more

You can find latest.log at http://pastebin.com/gNVGAyae and fml-client-latest.log at https://dl.dropboxusercontent.com/u/100868538/crash_log/fml-client-latest.log

**Comment by Tombenpotter** [comment]
The Soul Transposer has been fixed in 1.7.10-29, don't worry about that.
The crash you are getting simply means you need to change the IDs of the potions in Sanguimancy's config to be lower than 128. The default values are wrong, that's an error on my side that's already been fixed, and that will come with next version.

**Comment by Goju-Sulfam** [comment]
It is the "removeHeartPotionID" parameter ? It's set to 151. I suppose the maximum is 128, so "addHeartPotionID" is set to 150, is wrong too ?

**Comment by Tombenpotter** [comment]
Yes. Sadly, I derped :p

**Comment by Goju-Sulfam** [comment]
No problem. If it is just that, it is not so problematic. Thank for the fast answer

**Comment by Tombenpotter** [comment]
No worries! :)
