### ISSUE TITLE
Exception, when world loading.

### ISSUE THREAD

**Issue by fewizz** [Tombenpotter/Sanguimancy#73]
Exception when world loading.

[16:17:15] [Server thread/ERROR] [FML]: Caught exception from Sanguimancy
java.lang.ArrayIndexOutOfBoundsException: 2
	at tombenpotter.sanguimancy.util.RandomUtils.setTranspositionBlockBlacklist(RandomUtils.java:464) ~[RandomUtils.class:1.7.10-1.1.9-31]
	at tombenpotter.sanguimancy.Sanguimancy.serverStarting(Sanguimancy.java:110) ~[Sanguimancy.class:1.7.10-1.1.9-31]

**Comment by fewizz** [comment]
Oh sorry. I deleted config file, and now all works fine.
