### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 2

### ISSUE THREAD

**Issue by loordgek** [Tombenpotter/Sanguimancy#93]
it is not my mc that is crashing 
but his http://www.minecraftforge.net/forum/index.php/topic,35761.0.html

java.lang.ArrayIndexOutOfBoundsException: 2
   at tombenpotter.sanguimancy.util.RandomUtils.setTranspositionBlockBlacklist(RandomUtils.java:464) ~[RandomUtils.class:1.7.10-1.1.9-31]
   at tombenpotter.sanguimancy.Sanguimancy.serverStarting(Sanguimancy.java:110) ~[Sanguimancy.class:1.7.10-1.1.9-31]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
   at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
   at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
   at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
   at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
   at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
   at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at Reflector.callBoolean(Reflector.java:363) [Reflector.class:?]
   at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:161) [bsx.class:?]
   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[20:54:35] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
java.lang.ArrayIndexOutOfBoundsException: 2
   at tombenpotter.sanguimancy.util.RandomUtils.setTranspositionBlockBlacklist(RandomUtils.java:464) ~[RandomUtils.class:1.7.10-1.1.9-31]
   at tombenpotter.sanguimancy.Sanguimancy.serverStarting(Sanguimancy.java:110) ~[Sanguimancy.class:1.7.10-1.1.9-31]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
   at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
   at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
   at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
   at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
   at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
   at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
   at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
   at Reflector.callBoolean(Reflector.java:363) [Reflector.class:?]
   at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:161) [bsx.class:?]
   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by TehNut** [comment]
#74, #73, #63, #55, #56, #58, #59 

Search please.
